<r>22.10.2022 r.<r>
<h1><center>Assignment - part 1</center></h1>
<h2><center>Quantum Internship</center></h2>

<h3><center>Jakub Łuczka</center></h3>

In [86]:
# Import necessery modules

import numpy as np
import matplotlib.pyplot as plt
import timeit

<h3>Exersise 1.</h3>
<b>What is FOR loop?</b>

You have a positive integer number $N$ as an input. Please write a program in Python 3 that calculates the sum in range $1$ and $N$.

Limitations:
<li>$N <= 10^{25}$;</li>
<li>Execution time: $0.1$ seconds.</li>

<br>
Examples:
<li>Input: <b>1</b> -> Output: <b>1</b>,</li>

<li>Input: <b>3</b> -> Output: <b>6</b>,</li>

<li>Input: <b>10</b> -> Output: <b>55</b>.</li>


In [71]:
def sum_of_integers(n):
    '''Calculating sum of positive integers in 
    range from 1 to n using mathematical formula
    for this equation -> n * (n+1) / 2
    
    :param n : positive integer number
    :type n : integer
    
    :raises TypeError: if N is not an integer
    :raises ValueError: if N is smaller than 1
    
    :returns: sum of integers between 1 and N'''
    
    if type(n) != int:
        raise TypeError('Type of N is not integer!')
        
    if n < 1:
        raise ValueError('n must be positive!')
    
    number, next_integer = n, n+1
    return int(number * next_integer / 2)


In [85]:
starttime = timeit.default_timer()
sum_of_integers(6)
print("The time difference is :", timeit.default_timer() - starttime)

The time difference is : 0.000246300000071642


In [88]:
starttime = timeit.default_timer()
sum_of_integers(10)
print("The time difference is :", timeit.default_timer() - starttime)

The time difference is : 0.0002803000002131739


In [87]:
starttime = timeit.default_timer()
sum_of_integers(10**25)
print("The time difference is :", timeit.default_timer() - starttime)

The time difference is : 0.0002918999998655636


<h3>Exercise 2.</h3>

<b>Counting islands</b>

You have a matrix $M$x$N$ that represents a map. There are 2 possible states on the map: 1 - islands, 0 - ocean. Your task is to calculate the number of islands in the most effective way. Please write code in Python 3.

Inputs: $M$x$N$

Examples: 

<li>Input: 3x3, Output: 2</li>
<br>
$\left( \begin{array}{ccc}
0 & 1 & 0 \\
0 & 0 & 0 \\
0 & 1 & 1 \end{array} \right)$

<li>Input: 3x4, Output: 3</li> 
<br>
$\left( \begin{array}{cccc}
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \end{array} \right)$

<li>Input: 3x4, Output: 2</li>
<br>
$\left( \begin{array}{cccc}
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 1 \\
0 & 1 & 0 & 1 \end{array} \right)$

In [176]:
def island_creator(m, n, p):
    '''Function which creates an island based on squared
    numpy.array size m x n with probability of existing
    equal to p
    
    :param m : size of the lattice edge (number of rows)
    :type m : int
    
    :param n : size of the lattice edge (number of columns)
    :type n : int
    
    :param p : probability of island exisiting
    :type p : float
    
    :returns: a forest based on numpy.array with ones 
    meaning trees and zeros and meaning empty space'''
    
    ocean_matrix = np.zeros(shape = (m, n))

    for i in range(m):
        for j in range(n):
            if np.random.uniform() <= p:
                ocean_matrix[i][j] = 1
    
    return ocean_matrix


In [177]:
m, n, p = 5, 6, 0.4
island_creator(m, n, p)

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 1.]])

In [189]:
def cluster_searching(island):
    '''Searching for the biggest cluster of smoked trees in forest
    based on Hoshen-Kopelman algorithm, but with consideration of
    crossing neighbours
        
    : param forest : final step of burning forest with three states 
                     0 - empty space, 1 - trees and 3 - smoked trees 
    : type forest : np.array
       
    :returns: size of the biggest cluster (number of elements with the
    same ID)'''
    
    # Help function used to merge labels if there any revisions        
    def ID_merging(merged, to):
        for m in merged:
            labels[labels == m] = to
            if m != to:
                ID_list.remove(m)
                
    ID_list = []
    actual_ID = 1
    m, n = island.shape[0], island.shape[1]
    labels = np.zeros((m, n))
    
    # Going through all elements in forest array
    for i in range(m):
        for j in range(n):
            # Checking for smoked trees
            if island[i, j] == 1:
                neighbours_ID_list = []
                neighbourhood = [(i-1, j), (i, j-1)]
                # Looking for IDs of the neighbourhood
                for first_neighbour, second_neighbour in neighbourhood:
                    # Be sure that element exists in array
                    if first_neighbour >= 0 and second_neighbour >= 0:
                        if island[first_neighbour, second_neighbour] == 1:
                            if labels[first_neighbour, second_neighbour] not in neighbours_ID_list:
                                neighbours_ID_list.append(labels[first_neighbour, second_neighbour])

                if not neighbours_ID_list:
                    # Adding new ID to main list
                    labels[i, j] = actual_ID
                    ID_list.append(actual_ID)
                    actual_ID = actual_ID + 1
                else:
                    # Taking minimum of IDs and changing ID for all neighbourhood
                    labels[i, j] = min(neighbours_ID_list)
                    ID_merging(neighbours_ID_list, min(neighbours_ID_list))
    
    return len(ID_list)


In [190]:
m, n, p = 6, 7, 0.4
island = island_creator(m, n, p)
island

array([[0., 0., 1., 1., 1., 0., 0.],
       [1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1., 0., 0.]])

In [191]:
cluster_searching(island)

2

In [192]:
m, n, p = 8, 8, 0.4
island = island_creator(m, n, p)
island

array([[1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 1., 1., 0., 0., 1., 1.],
       [1., 0., 1., 0., 1., 0., 0., 1.],
       [1., 1., 0., 0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 0.]])

In [193]:
cluster_searching(island)

8

In [194]:
m, n, p = 10, 10, 0.4
island = island_creator(m, n, p)
island

array([[0., 1., 0., 0., 0., 0., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0., 1., 0., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 1., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 1., 1., 0.],
       [1., 0., 1., 0., 1., 1., 0., 0., 0., 1.]])

In [195]:
cluster_searching(island)

10